import type { EnemyDef } from './types';

export const ENEMIES: Record<string, EnemyDef> = {
  tick: {
    id: 'tick',
    name: 'Hull Tick',
    hp: 11,
    biomass: 3,
    flavor: 'It fed on the hull. Now it has found something softer.',
    pattern: [
      { label: 'Frenzy', attack: 5, hits: 2 },
      { label: 'Burrow', block: 2, attack: 5 },
      { label: 'Bite', attack: 8 },
    ],
  },
  copy: {
    id: 'copy',
    name: 'Mewling Copy',
    hp: 20,
    biomass: 5,
    flavor: 'A misprint. It has your hands. It wants the rest.',
    pattern: [
      { label: 'Claw', attack: 9 },
      { label: 'Weep', weak: 2, line: '“why did they keep you”' },
      { label: 'Maul', attack: 13 },
    ],
  },
  husk: {
    id: 'husk',
    name: 'Custodian Husk',
    hp: 26,
    biomass: 6,
    flavor: 'Maintenance drone. It wears a face it found in the vats.',
    pattern: [
      { label: 'Plate & Jab', block: 3, attack: 8 },
      { label: 'Sweep', attack: 14 },
      { label: 'Diagnose', exposed: 2, line: 'SPECIMEN DEFECTIVE. RECYCLING.' },
    ],
  },
  drone: {
    id: 'drone',
    name: 'Sentry Drone',
    hp: 20,
    biomass: 5,
    flavor: 'It doesn’t see you. It doesn’t need to.',
    pattern: [
      { label: 'Lock On', exposed: 1, line: 'TARGET ACQUIRED' },
      { label: 'Volley', attack: 7, hits: 2 },
      { label: 'Overcharge', strength: 2, block: 2 },
    ],
  },
  bloom: {
    id: 'bloom',
    name: 'Vat Bloom',
    hp: 26,
    biomass: 6,
    flavor: 'It grew from what the vats couldn’t use. It is still growing.',
    pattern: [
      { label: 'Swell', block: 3 },
      { label: 'Spores', weak: 2, line: 'the air tastes like copper' },
      { label: 'Thrash', attack: 11 },
    ],
  },
  first: {
    id: 'first',
    name: 'The First',
    hp: 96,
    biomass: 16,
    flavor: 'The original. Every clone since was a rough draft of this.',
    pattern: [
      { label: 'Recognize', weak: 1, line: 'i remember being you' },
      { label: 'Backhand', attack: 15 },
      { label: 'We Are Legion', strength: 3, block: 4, line: 'they are all still in here' },
      { label: 'Cascade', attack: 10, hits: 2 },
    ],
  },
  choir: {
    id: 'choir',
    name: 'The Choir',
    hp: 78,
    biomass: 12,
    flavor: 'Every clone that died here. They learned to sing together.',
    pattern: [
      { label: 'Hymn', attack: 11, line: 'WE WERE YOU FIRST' },
      { label: 'Swell', block: 4, strength: 2, line: 'come home come home come home' },
      { label: 'Crescendo', attack: 9, hits: 2 },
      { label: 'Dirge', weak: 2, exposed: 1, line: 'you are the same meat' },
    ],
  },

  // ---- Kessra (Glass Caves) ----
  shardling: {
    id: 'shardling',
    name: 'Shardling',
    hp: 12,
    biomass: 2,
    splits: true,
    flavor: 'A splinter that learned to walk. Break it and there are two.',
    pattern: [
      { label: 'Nip', attack: 6 },
      { label: 'Skitter', attack: 8 },
      { label: 'Nip', attack: 7 },
    ],
  },
  crawler: {
    id: 'crawler',
    name: 'Lattice Crawler',
    hp: 36,
    biomass: 6,
    flavor: 'It grows armour faster than you can cut it. Hit it before it finishes.',
    pattern: [
      { label: 'Harden', block: 4 },
      { label: 'Grind', block: 3, attack: 10 },
      { label: 'Crush', attack: 17 },
    ],
  },
  geode: {
    id: 'geode',
    name: 'Singing Geode',
    hp: 18,
    biomass: 5,
    flavor: 'It never attacks. It sings, and everything near it gets stronger.',
    pattern: [
      { label: 'Hum', allyStrength: 2, line: 'mmmmmmmmmm' },
      { label: 'Shriek', weak: 1, exposed: 1 },
      { label: 'Chorus', allyStrength: 2, block: 2 },
    ],
  },
  refractor: {
    id: 'refractor',
    name: 'Refractor',
    hp: 52,
    biomass: 10,
    reflect: 0.5,
    flavor: 'A walking mirror. While it is plated, half of every blow comes back to you.',
    pattern: [
      { label: 'Polish', block: 4 },
      { label: 'Lance', attack: 14 },
      { label: 'Glare', attack: 10, block: 3 },
    ],
  },
  prism: {
    id: 'prism',
    name: 'The Prism Mother',
    hp: 150,
    biomass: 18,
    flavor: 'The oldest thing in the caves. Every shardling is a piece she let go of.',
    pattern: [
      { label: 'Refract', attack: 11, hits: 2 },
      { label: 'Glare', weak: 2, exposed: 1, line: 'I SEE EVERY COPY OF YOU' },
      { label: 'Prism Beam', attack: 19 },
      { label: 'Facet', block: 5 },
    ],
    phase2: {
      below: 0.5,
      line: 'THEN BREAK. AND BREAK. AND BREAK.',
      pattern: [
        { label: 'Shed', summon: 'shardling', attack: 9 },
        { label: 'Spectrum', attack: 11, hits: 2 },
        { label: 'Shed', summon: 'shardling', block: 4 },
        { label: 'Prism Beam', attack: 21 },
      ],
    },
  },
};
